# Generated by Django 4.1 on 2022-08-10 04:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geprapapp', '0002_permisos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rol_Permisos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permiso', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='geprapapp.permisos')),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='geprapapp.roles')),
            ],
        ),
    ]
