# Generated by Django 4.1 on 2022-08-15 03:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geprapapp', '0006_categoria_producto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('Producto', models.CharField(max_length=500)),
                ('fecha_pedido', models.DateField()),
                ('total', models.IntegerField()),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='geprapapp.usuarios')),
            ],
        ),
    ]
