# Generated by Django 4.1 on 2022-08-15 03:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geprapapp', '0007_pedido'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto_Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('id_Pedido', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='geprapapp.pedido')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='geprapapp.producto')),
            ],
        ),
    ]
