# Generated by Django 4.1 on 2022-08-15 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geprapapp', '0009_alter_producto_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='Producto',
        ),
    ]
