# Generated by Django 4.1 on 2022-08-15 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geprapapp', '0010_remove_pedido_producto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto_pedido',
            old_name='producto',
            new_name='id_producto',
        ),
    ]
