# Generated by Django 4.1 on 2022-08-15 04:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geprapapp', '0012_servicio_servicio_pedido'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ventas',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('id_Pedido', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='geprapapp.pedido')),
            ],
        ),
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('fecha_asignada', models.DateField()),
                ('id_venta', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='geprapapp.ventas')),
            ],
        ),
    ]
