# Generated by Django 4.1 on 2022-08-21 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geprapapp', '0013_ventas_agenda'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Roles',
            new_name='Rol',
        ),
    ]
