# Generated by Django 4.1 on 2022-08-21 21:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geprapapp', '0014_rename_roles_rol'),
    ]

    operations = [
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('fechaEntregaProducto', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Metodo_Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metodoPago', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameModel(
            old_name='Ventas',
            new_name='Venta',
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plazos', models.IntegerField()),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='geprapapp.factura')),
                ('formaPago', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='geprapapp.metodo_pago')),
            ],
        ),
        migrations.AddField(
            model_name='factura',
            name='id_venta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='geprapapp.venta'),
        ),
    ]
