# Generated by Django 4.1 on 2022-08-21 21:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geprapapp', '0015_factura_metodo_pago_rename_ventas_venta_pago_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Permisos',
            new_name='Permiso',
        ),
        migrations.RenameModel(
            old_name='Rol_Permisos',
            new_name='Rol_Permiso',
        ),
        migrations.RenameModel(
            old_name='Usuarios',
            new_name='Usuario',
        ),
        migrations.CreateModel(
            name='Garantia',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('descripcion', models.TextField()),
                ('fechaGarantia', models.DateField()),
                ('id_venta', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='geprapapp.venta')),
            ],
        ),
    ]
