# Generated by Django 4.1 on 2022-09-13 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geprapapp', '0018_alter_producto_pedido_id_alter_servicio_pedido_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='desc',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
