# Generated by Django 4.1 on 2022-09-18 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geprapapp', '0020_alter_servicio_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
