# Generated by Django 4.1 on 2022-10-09 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geprapapp', '0021_alter_agenda_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rol_permiso',
            name='permiso',
        ),
        migrations.RemoveField(
            model_name='rol_permiso',
            name='rol',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='rol',
        ),
        migrations.AlterField(
            model_name='evaluacion',
            name='calificacionEvaluacion',
            field=models.TextField(),
        ),
        migrations.DeleteModel(
            name='Permiso',
        ),
        migrations.DeleteModel(
            name='Rol',
        ),
        migrations.DeleteModel(
            name='Rol_Permiso',
        ),
    ]
