# Generated by Django 4.1 on 2022-10-09 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geprapapp', '0022_remove_rol_permiso_permiso_remove_rol_permiso_rol_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='clave',
            field=models.CharField(default=12345, max_length=254),
        ),
        migrations.AddField(
            model_name='usuario',
            name='nombreUsuario',
            field=models.TextField(default='admin', max_length=100),
        ),
        migrations.AddField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('A', 'Administrador'), ('E', 'Empleado'), ('O', 'Operario'), ('C', 'Cliente'), ('I', 'Instalador')], default='E', max_length=100),
        ),
    ]
