# Generated by Django 4.1 on 2022-11-17 04:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geprapapp', '0024_remove_servicio_pedido_id_pedido_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pago',
            name='factura',
        ),
        migrations.AddField(
            model_name='pago',
            name='pedido',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='geprapapp.pedido'),
        ),
        migrations.DeleteModel(
            name='Factura',
        ),
    ]
