# Generated by Django 4.1 on 2022-11-17 05:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geprapapp', '0025_remove_pago_factura_pago_pedido_delete_factura'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='geprapapp.pedido'),
        ),
    ]
