# Generated by Django 4.1 on 2022-11-17 05:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geprapapp', '0026_alter_pago_pedido'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evaluacion',
            name='id_venta',
        ),
        migrations.RemoveField(
            model_name='garantia',
            name='id_venta',
        ),
        migrations.AddField(
            model_name='evaluacion',
            name='pedido',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='geprapapp.pedido'),
        ),
        migrations.AddField(
            model_name='garantia',
            name='pedido',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='geprapapp.pedido'),
        ),
    ]
