# Generated by Django 4.1 on 2022-11-17 05:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geprapapp', '0028_evaluacion_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluacion',
            name='comentarios',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='evaluacion',
            name='pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='geprapapp.pedido'),
        ),
        migrations.AlterField(
            model_name='evaluacion',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='geprapapp.usuario'),
        ),
    ]
