# Generated by Django 4.1 on 2022-11-17 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geprapapp', '0029_alter_evaluacion_comentarios_alter_evaluacion_pedido_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluacion',
            name='comentarios',
            field=models.TextField(null=True),
        ),
    ]
