# Generated by Django 4.1 on 2022-11-17 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geprapapp', '0030_alter_evaluacion_comentarios'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluacion',
            name='comentarios',
            field=models.TextField(),
        ),
    ]
