# Generated by Django 4.1 on 2022-11-17 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geprapapp', '0031_alter_evaluacion_comentarios'),
    ]

    operations = [
        migrations.AlterField(
            model_name='garantia',
            name='pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='geprapapp.pedido'),
        ),
    ]
