# Generated by Django 4.1 on 2022-11-17 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geprapapp', '0033_remove_agenda_id_venta_agenda_pedido'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Venta',
        ),
    ]
