# Generated by Django 4.1 on 2022-11-17 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geprapapp', '0035_alter_agenda_pedido'),
    ]

    operations = [
        migrations.CreateModel(
            name='Detalle_Pedido',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('id_Pedido', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='geprapapp.pedido')),
                ('id_producto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='geprapapp.producto')),
                ('id_servicio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='geprapapp.servicio')),
            ],
        ),
    ]
