# Generated by Django 4.1 on 2022-11-17 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geprapapp', '0037_alter_detalle_pedido_id_producto_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detalle_pedido',
            old_name='id_Pedido',
            new_name='id_pedido',
        ),
    ]
