# Generated by Django 4.1 on 2022-11-26 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geprapapp', '0038_rename_id_pedido_detalle_pedido_id_pedido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('A', 'Administrador'), ('O', 'Operario'), ('C', 'Cliente'), ('I', 'Instalador')], default='E', max_length=100),
        ),
    ]
