# Generated by Django 4.1 on 2022-11-28 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geprapapp', '0039_alter_usuario_rol'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='estado',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
