# Generated by Django 4.1 on 2022-11-28 06:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geprapapp', '0043_alter_pedido_estado_alter_usuario_cedula_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalle_pedido',
            name='id_producto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='geprapapp.producto'),
        ),
        migrations.AlterField(
            model_name='detalle_pedido',
            name='id_servicio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='geprapapp.servicio'),
        ),
    ]
