# Generated by Django 4.1 on 2022-11-28 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geprapapp', '0047_alter_categoria_nombre_alter_usuario_correo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metodo_pago',
            name='metodoPago',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='producto',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
