# Generated by Django 4.1 on 2022-11-29 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geprapapp', '0049_alter_evaluacion_id_alter_garantia_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='correo',
            field=models.EmailField(max_length=250, unique=True),
        ),
    ]
