# Generated by Django 4.1 on 2022-12-03 22:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geprapapp', '0052_detalle_pedido_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalle_pedido',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='geprapapp.usuario'),
        ),
    ]
